apiVersion: v1
kind: Service
metadata :
  name: node-client-service
spec:
  selector:
    app: node-client
  type: NodePort
  ports: 
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31111
  - name: https
    protocol: TCP
    port: 9377
    targetPort: 9377
    nodePort: 31112
