apiVersion: v1
kind: Service
metadata :
  name: back-mongo-service
spec:
  selector:
    app: back-mongo
  type: NodePort
  ports: 
  - protocol: TCP
    port : 27017
    targetPort: 27017
    nodePort: 31716